### ISSUE TITLE
README.mdの整理、CONTRIBUTING.md や LICENSE.txt の追加

### ISSUE THREAD

**Issue by xuwei-k** [scalajp/2014.scalamatsuri.org#2]

**Comment by tkawachi** [comment]
> ライセンスが明記されていないソースコードに対しては、このページにあるように、デフォルトの著作権法が適用されます。
> つまり、ソフトウェアの複製、改変、（複製物または二次的著作物の）再頒布が認められません。

http://qiita.com/shibukk/items/67ad0a5eda5a94e5c032

Slack で明記なしで行こうとまとまったと思いますので、閉じます。
